apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: web-tier
  labels:
    app.kubernetes.io/name: frontend-loadbalancer
    app.kubernetes.io/part-of: review-analysis-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: web-tier
  labels:
    app.kubernetes.io/name: backend-loadbalancer
    app.kubernetes.io/part-of: review-analysis-system
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: backend