# EKS Migration - Redis Exporter for Monitoring
# Task 6.1: Redis 메트릭 수집을 위한 Exporter 배포

---
# Redis Exporter Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: cache-tier
  labels:
    app: redis-exporter
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/part-of: review-analysis-system
    app.kubernetes.io/component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.55.0
        env:
        - name: REDIS_ADDR
          value: "redis://redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
              optional: true
        ports:
        - containerPort: 9121
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 5
          periodSeconds: 10

---
# Redis Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
  namespace: cache-tier
  labels:
    app: redis-exporter
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/part-of: review-analysis-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: redis-exporter
  type: ClusterIP
  ports:
  - port: 9121
    targetPort: 9121
    name: metrics