apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
rules:
  - apiGroups: ["", "apps", "batch", "extensions", "rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-readonly
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-readonly
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-readonly
subjects:
  - kind: ServiceAccount
    name: airflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admins
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: airflow-namespace-admins
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-standard
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
spec:
  hard:
    pods: "50"
    requests.cpu: "20"
    requests.memory: "40Gi"
    limits.cpu: "40"
    limits.memory: "80Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-defaults
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  labels:
    app.kubernetes.io/part-of: reviews-analytics
    app.kubernetes.io/managed-by: kustomize
    owner: data-platform
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
