apiVersion: batch/v1
kind: Job
metadata:
  name: setup-backend-db
  namespace: web-tier
spec:
  template:
    spec:
      containers:
      - name: postgres-client
        image: postgres:17-alpine
        env:
        - name: PGPASSWORD
          value: "NewSecurePassword2024!"
        command:
        - /bin/sh
        - -c
        - |
          psql -h airflow-metadata-db.cxkoo6wi2dyy.ap-northeast-2.rds.amazonaws.com -U postgres -d postgres -f /sql/setup-backend-database.sql
        volumeMounts:
        - name: sql-script
          mountPath: /sql
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: sql-script
        configMap:
          name: setup-db-sql
      restartPolicy: Never
  backoffLimit: 3