# airflow-values.yaml
# Airflow 버전 2.8.1 이상을 권장합니다.
# https://github.com/apache/airflow/tree/main/chart/values.yaml 에서 최신 버전 확인

images:
  airflow:
    repository: apache/airflow
    tag: 3.0.2
    pullPolicy: IfNotPresent

# KubernetesExecutor 사용
executor: KubernetesExecutor 

# Python 및 기타 라이브러리 추가 설치
airflow:
  extraPipPackages:
#    - "apache-airflow-providers-apache-kafka"
#    - "apache-airflow-providers-postgres"
#    - "psycopg2-binary"
    - "kafka-python"

# # Kafka 연결을 위한 환경변수 설정
# config:
#   AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
#   AIRFLOW__KAFKA__BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
#   AIRFLOW__KAFKA__TEST_TOPIC: "test.airflow.kafka"

# # Kafka Connection 설정
# connections:
#   - conn_id: "kafka_default"
#     conn_type: "kafka"
#     host: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"


# DAG 동기화 설정 (Git Sync)
dags:
  # Git Sync 설정
  gitSync:
    enabled: true
    repo: https://github.com/KOSA-CloudArchitect/airflow.git
    branch: main
    subPath: dags
    # subPath를 제거하여 Git 저장소 루트의 dags 폴더를 /opt/airflow/dags에 마운트


# 내부 Postgres 사용 (차트 내 postgresql 서브차트)
data:
  metadataConnection:
    user: "postgres"
    pass: "airflow"
    protocol: postgresql
    host: "34.64.178.184"
    port: 5432
    db: "postgres"
    sslmode: disable
    # Add custom annotations to the metadata connection secret
    secretAnnotations: {}

# # 외부 데이터베이스 설정 (PostgreSQL)
postgresql:
  enabled: false # 차트 내장 DB 사용 안 함

# externalDatabase:
#   type: postgres
#   host: "34.64.178.184"
#   port: 5432
#   user: "postgres"
#   #password: "airflow"
#   passwordSecret: "airflow-postgresql" # DB credentials secret 이름
#   database: "postgres"

# 외부 데이터베이스 설정 (PostgreSQL)
# metadataConnection:
#   user: "postgres"
#   pass: "airflow"
#   protocol: postgresql
#   host: "34.64.178.184"
#   port: 5432
#   db: "postgres"
#   sslmode: disable



webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin

# triggerer:
#   replicas: 1
#   resources:
#     requests:
#       cpu: "50m" # 리소스 요청을 낮춰봅니다.
#       memory: "128Mi"

# Airflow Webserver, Scheduler, Worker 리소스 설정 (필요에 따라 조절)
# 예시:
# scheduler:
#   resources:
#     requests:
#       cpu: "500m"
#       memory: "1Gi"
#   replicas: 2 # 고가용성 설정


