apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: realtime-review-collection-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1        # 필요 처리량/키 분포에 맞춰 조정
  replicas: 1          # 브로커 수 이상으로 설정하지 말 것(보통 3 권장)
  config:
    cleanup.policy: delete
    retention.ms: 604800000    # 7일(예시) — 원하면 줄이거나 늘리세요
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: realtime-review-transform-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 604800000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: realtime-review-analysis-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: review-agg-by-job
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: compact,delete
    retention.ms: 1209600000  # 14일
    min.cleanable.dirty.ratio: 0.1
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: review-rows
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 1
  config:
    cleanup.policy: delete
    retention.ms: 1209600000
    segment.bytes: 1073741824