# deployment.spec.template.spec:
volumes:
  - name: frontend-env
    configMap:
      name: frontend-env
      items:
        - key: env.js
          path: env.js
containers:
  - name: frontend
    volumeMounts:
      - name: frontend-env
        mountPath: /usr/share/nginx/html/env.js  # Nginx 정적 루트 예시
        subPath: env.js