# patch-imagepullsecret.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: web-tier
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ecr-web-server-secret
